[package]
name = "rcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
dotenvy = "0.15.7"

[dev-dependencies]
assert_cmd = "2.0.13"
